### PR TITLE
SOC and ROT now caluclated in separate modules, both are  called from…

### PR DESCRIPTION
**Pull request by wdednam**
… spin_orbit in device.F90

### CODE REVIEW

**Comment by juanjosepalacios** [comment]
The keywords THETA and PHI are now useless, aren't they?

**Comment by juanjosepalacios** [comment]
A minor issue. To easily remember, can we use SPINROTATOM instead of SPINROT, to make similar to SOCFACATOM? This way we know that what follows is an individual atom by atom assignment.

**Comment by wdednam** [comment]
> The keywords THETA and PHI are now useless, aren't they?

I guess so. I can remove them. Unless you want to rotate all the spins at once by the same angles?

**Comment by wdednam** [comment]
> A minor issue. To easily remember, can we use SPINROTATOM instead of SPINROT, to make similar to SOCFACATOM? This way we know that what follows is an individual atom by atom assignment.

Very good suggestion. On it.

**Comment by wdednam** [comment]
> The keywords THETA and PHI are now useless, aren't they?

In SpinRotate.F90, on lines 156-162, the values of theta and phi of the individual spins default to THETA and PHI if NSpinRot=0:

                    IF( NSpinRot > 0) THEN
                      theta_atom = SpinRotTheta(AtomID2)
                      phi_atom = SpinRotPhi(AtomID2)
                    ELSE
                      theta_atom = theta
                      phi_atom = phi	
                    END IF   
I don't know if global rotations will be useful, especially when there are mixed species in the input, so I can remove this condition if you like?

**Pull request merged**
