### PR TITLE
github did not update all code changes I committed

### PR DESCRIPTION
**Pull request by wdednam**

### CODE REVIEW

**Comment by wdednam** [comment]
> so this is the Zeeman term working for arbitrary orientations of B?

Yes, there were instances of ZM missing from in other subroutines, which I don't understand why Github did not add. Now they are correct.

**Comment by juanjosepalacios** [comment]
OK, I will give it a go when I have some time, but I will merge it anyway

**Comment by juanjosepalacios** [comment]
Is it already merged?

**Comment by wdednam** [comment]
> Is it already merged?

Yes. I went ahead and merged it because the changes are few and easy to see.

**Pull request merged**
